@echo off
rem ================================================================
rem  WinUtilKLENN v2.8.0 (fixed + optimized)
rem  Diagnostics and guided repair tools for Windows 10/11.
rem  Copyright (C) 2026 sanguirIS (https://github.com/sanguirIS)
rem  License: GNU GPL v3  -  NO WARRANTY, see <https://www.gnu.org/licenses/>
rem
rem  v2.8.0 CHANGES (bug-fix + speed + security pass):
rem   BUGFIX 1  Elevation relaunch now uses double-quoted path with
rem             escaped quotes so script paths containing spaces or
rem             apostrophes survive Start-Process.
rem   BUGFIX 2  Version-compare: parse x.y.z from tag and build a real
rem             [version]; falls back to string compare on bad tags.
rem   BUGFIX 3  Windows Update reset now waits for services to stop
rem             before renaming SoftwareDistribution/catroot2, with a
rem             10-second retry; renames verified before declaring OK.
rem   BUGFIX 4  :MENU invalid input no longer re-triggers an unhandled
rem             empty reparse; special chars are shown, not executed.
rem   BUGFIX 5  winget "No package found" detection now also checks
rem             errorlevel from winget show (older winget builds).
rem   BUGFIX 6  Battery report: powercfg errorlevel verified before
rem             opening the HTML file.
rem   SPEED 1   :RESIZE now runs ONCE per session (RESIZE_DONE flag) and
rem             only again when the console width changed - no more
rem             PowerShell spawn on every screen (~1-2 s saved/screen).
rem   SPEED 2   ICONS + LOGO are generated by ONE PowerShell call
rem             instead of one call per symbol.
rem   SPEED 3   Long repair ops now show an animated spinner while they
rem             run (visual feedback instead of a frozen window).
rem   SPEED 4   DNS/Network checks use one consolidated PowerShell call.
rem   TEXT FIT  RULE_BIG / RULE_SMALL auto-fit the current console
rem             width (never wrap, never truncate) and the menu is
rem             re-measured if the window is resized mid-session.
rem   ANIME/ANIM  Neon-anime styled animated boot banner: gradient
rem             logo, animated loading dots, typewriter tagline.
rem             VT processing is force-enabled via SetConsoleMode so
rem             colours work on every Windows 10/11 host.
rem   SECURITY  New SECURITY section (option 25): Defender status +
rem             quick scan, firewall profile check, UAC level check,
rem             log rotation (log capped at 512 KB) and TLS 1.2 forced
rem             on every download.
rem ================================================================
chcp 65001 >nul
setlocal EnableExtensions
title WinUtilKLENN
color 0F

set "LOGDIR=%ProgramData%\WinUtilKLENN"
set "LOGFILE=%LOGDIR%\WinUtilKLENN.log"
set "VERSION=v2.8.0"
set "CON_WIDTH=68"
set "RESIZE_DONE=0"

if not exist "%LOGDIR%" mkdir "%LOGDIR%" >nul 2>&1

rem ------- Force-enable VT (ANSI) processing so colours always work ----
powershell.exe -NoProfile -Command "$k=[Console]::get_Type(); $m=$k.GetMethod('GetStdHandle',[reflection.bindingflags]'Static,Public,NonPublic,Instance', $null, @([int32]), $null); $m2=$k.GetMethod('SetConsoleMode',[reflection.bindingflags]'Static,Public,NonPublic,Instance', $null, @([intptr],[int32]), $null); $h=$m.Invoke($null, @(-11)); $old=0; $mode=0; $g=$k.GetMethod('GetConsoleMode',[reflection.bindingflags]'Static,Public,NonPublic,Instance', $null, @([intptr],[int32].MakeByRefType()), $null); $g.Invoke($null, @($h, [ref]$mode))|Out-Null; $m2.Invoke($null, @($h, $mode -bor 4))|Out-Null" >nul 2>&1

rem ------- ANSI colour engine ---------------------------------------
for /f %%a in ('echo prompt $E ^| cmd') do set "ESC=%%a"
set "R=%ESC%[0m"
set "BOLD=%ESC%[1m"
set "DIM=%ESC%[2m"
set "BLK=%ESC%[30m"
set "RED=%ESC%[31m"
set "GRN=%ESC%[32m"
set "YLW=%ESC%[33m"
set "CYN=%ESC%[36m"
set "WHT=%ESC%[37m"
set "MAG=%ESC%[35m"
set "BRED=%ESC%[91m"
set "BGRN=%ESC%[92m"
set "BYLW=%ESC%[93m"
set "BCYN=%ESC%[96m"
set "BWHT=%ESC%[97m"
set "BMAG=%ESC%[95m"
set "BGRED=%ESC%[41m"
set "BGGRN=%ESC%[42m"
set "BGYLW=%ESC%[43m"
set "BGBLU=%ESC%[44m"
set "BGMAG=%ESC%[45m"
set "BGCYN=%ESC%[46m"
set "BGGRAD=%ESC%[48;2;255;105;180m"

rem ------- Icons, rules and text-fit metrics (ONE PowerShell call) ---
rem  RULE sizes adapt to the real console width (auto-fit, no wrap).
set "SYM_ARROW=>"
set "SYM_OK=v"
set "SYM_NO=x"
set "SYM_BULLET=o"
set "RULE_BIG="
set "RULE_SMALL="
set "CON_WIDTH=68"
for /f "tokens=1-8 delims=|" %%a in ('powershell -NoProfile -Command "$ErrorActionPreference='SilentlyContinue'; $w=[Math]::Max(60,[Math]::Min(100,(Get-Host).UI.RawUI.WindowSize.Width)); $h=[char]0x2500; $a=[char]0x25BA; $o=[char]0x2713; $x=[char]0x2717; $b=[char]0x25CF; $s=[char]0x2605; Write-Output ($a.ToString()+'|'+$o.ToString()+'|'+$x.ToString()+'|'+$b.ToString()+'|'+$s.ToString()+'|'+($h.ToString()*($w-2))+'|'+($h.ToString()*36)+'|'+$w)"') do (
    set "SYM_ARROW=%%a"
    set "SYM_OK=%%b"
    set "SYM_NO=%%c"
    set "SYM_BULLET=%%d"
    set "SYM_STAR=%%e"
    set "RULE_BIG=%%f"
    set "RULE_SMALL=%%g"
    set "CON_WIDTH=%%h"
)
set "RESIZE_DONE=1"

rem ------- Security: rotate the log so it can never grow unbounded ----
call :SECLOGROTATE

rem ------- Animated anime boot banner ---------------------------------
call :ANIMEBOOT

rem ------- Optional test mode (skip elevation) -----------------------
rem  Set WINUTIL_TEST=1 to run the menu without the UAC prompt.
if /i "%WINUTIL_TEST%"=="1" goto MENU
rem ------- Self-elevate so repair actions can run --------------------
net session >nul 2>&1
if not "%errorlevel%"=="0" (
    echo.
    echo  %BYLW%!%R%  %BWHT%Administrator permission is required.%R%
    echo  %CYN%-%R%  %WHT%Please accept the UAC prompt, the tool restarts elevated...%R%
    rem  BUGFIX: double-quoted path - spaces and apostrophes in the script
    rem  path no longer break the elevation relaunch.
    powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath \"%~f0\" -Verb RunAs" >nul 2>&1
    if errorlevel 1 goto UAC_CANCELLED
    exit /b
)
echo [%date% %time%] Started >> "%LOGFILE%"
goto MENU

:UAC_CANCELLED
echo.
echo  %BYLW%!%R%  %WHT%Elevation cancelled - no changes were made.%R%
echo  %CYN%-%R%  %WHT%Some repair options need Administrator rights.%R%
echo  %CYN%-%R%  %WHT%Right-click this script and select %BOLD%"Run as administrator"%R%  %WHT%to use them.%R%
echo.
pause
exit /b

:MENU
cls
call :FITCHECK
echo.
echo  %RULE_BIG%
echo  %BOLD%%BGMAG%%BWHT%   WINUTILKLENN   %R% %BCYN%/%BMAG%%BMAG%/%R%
echo  %BCYN%      Diagnostics and Repair  %SYM_BULLET%  Windows 10 / 11  [ %VERSION% ]%R%
echo  %RULE_BIG%
echo.
echo  %BOLD%%CYN%  MEDIA%R%
echo     %BCYN%%BOLD%1%R%  %SYM_ARROW%  %WHT%Audio%R%
echo     %BCYN%%BOLD%2%R%  %SYM_ARROW%  %WHT%Video Playback%R%
echo     %BCYN%%BOLD%3%R%  %SYM_ARROW%  %WHT%Windows Media Player%R%
echo.
echo  %BOLD%%CYN%  CONNECTIVITY%R%
echo     %BCYN%%BOLD%4%R%  %SYM_ARROW%  %WHT%Network and Internet%R%
echo     %BCYN%%BOLD%5%R%  %SYM_ARROW%  %WHT%DNS Flush%R%
echo     %BCYN%%BOLD%6%R%  %SYM_ARROW%  %WHT%Bluetooth%R%
echo.
echo  %BOLD%%CYN%  DEVICES%R%
echo     %BCYN%%BOLD%7%R%  %SYM_ARROW%  %WHT%Printer%R%
echo     %BCYN%%BOLD%8%R%  %SYM_ARROW%  %WHT%Camera%R%
echo     %BCYN%%BOLD%9%R%  %SYM_ARROW%  %WHT%Graphics Driver Reset%R%
echo.
echo  %BOLD%%CYN%  WINDOWS UPDATE%R%
echo    %BCYN%%BOLD%10%R%  %SYM_ARROW%  %WHT%Windows Update%R%
echo    %BCYN%%BOLD%11%R%  %SYM_ARROW%  %WHT%BITS%R%
echo.
echo  %BOLD%%CYN%  MAINTENANCE%R%
echo    %BCYN%%BOLD%12%R%  %SYM_ARROW%  %WHT%Disk Cleanup%R%
echo    %BCYN%%BOLD%13%R%  %SYM_ARROW%  %WHT%Restore Point%R%
echo    %BCYN%%BOLD%14%R%  %SYM_ARROW%  %WHT%Battery Report%R%
echo    %BCYN%%BOLD%15%R%  %SYM_ARROW%  %WHT%Restart / Shutdown%R%
echo    %BCYN%%BOLD%16%R%  %SYM_ARROW%  %WHT%winget Upgrade%R%
echo.
echo  %BOLD%%CYN%  SECURITY%R%
echo    %BCYN%%BOLD%25%R%  %SYM_ARROW%  %WHT%Security Check (Defender / Firewall / UAC)%R%
echo.
echo  %BOLD%%CYN%  OTHER / TOOLS%R%
echo    %BCYN%%BOLD%17%R%  %SYM_ARROW%  %WHT%Yoinks - Video Downloader%R%
echo    %BCYN%%BOLD%18%R%  %SYM_ARROW%  %WHT%ghgrab - GitHub Downloader%R%
echo    %BCYN%%BOLD%19%R%  %SYM_ARROW%  %WHT%Freebuff - AI Agent%R%
echo    %BCYN%%BOLD%20%R%  %SYM_ARROW%  %WHT%Program Compatibility%R%
echo    %BCYN%%BOLD%21%R%  %SYM_ARROW%  %WHT%Run ALL Diagnostics%R%
echo    %BCYN%%BOLD%22%R%  %SYM_ARROW%  %WHT%System Summary%R%
echo    %BCYN%%BOLD%23%R%  %SYM_ARROW%  %WHT%Check for Updates%R%
echo    %BCYN%%BOLD%24%R%  %SYM_ARROW%  %WHT%Chris Titus Tech WinUtil%R%
echo     %BCYN%%BOLD%0%R%  %SYM_ARROW%  %WHT%Exit%R%
echo.
echo  %RULE_BIG%
echo  %DIM%  Log: %LOGFILE%%R%
echo  %DIM%  WinUtilKLENN  Copyright (C) 2026 sanguirIS%R%
echo  %DIM%  This program comes with ABSOLUTELY NO WARRANTY.%R%
echo  %DIM%  Free software: redistribute under the GNU GPL v3 - see LICENSE%R%
echo.
set "CHOICE="
set /p "CHOICE=%BOLD%%BWHT%  Select an option %R%%CYN%[0-25]%R%%BOLD%%BWHT%: %R%"
if not defined CHOICE goto MENU
if "%CHOICE%"=="1" goto AUDIO
if "%CHOICE%"=="2" goto VIDEO
if "%CHOICE%"=="3" goto WMP
if "%CHOICE%"=="4" goto NETWORK
if "%CHOICE%"=="5" goto DNSFLUSH
if "%CHOICE%"=="6" goto BLUETOOTH
if "%CHOICE%"=="7" goto PRINTER
if "%CHOICE%"=="8" goto CAMERA
if "%CHOICE%"=="9" goto GFXRESET
if "%CHOICE%"=="10" goto UPDATE
if "%CHOICE%"=="11" goto BITS
if "%CHOICE%"=="12" goto DISKCLEAN
if "%CHOICE%"=="13" goto RESTOPOINT
if "%CHOICE%"=="14" goto BATTERY
if "%CHOICE%"=="15" goto POWER
if "%CHOICE%"=="16" goto WINGETUP
if "%CHOICE%"=="17" goto YOINK
if "%CHOICE%"=="18" goto GHGRAB
if "%CHOICE%"=="19" goto FREEBUFF
if "%CHOICE%"=="20" goto COMPAT
if "%CHOICE%"=="21" goto ALL
if "%CHOICE%"=="22" goto SUMMARY
if "%CHOICE%"=="23" goto UPDATECHECK
if "%CHOICE%"=="24" goto WINUTIL
if "%CHOICE%"=="25" goto SECURITY
if "%CHOICE%"=="0" goto END
echo.
echo  %BRED%!%R%  %WHT%Invalid selection: %CHOICE%%R%
echo.
pause
goto MENU

rem ================================================================
rem  1. AUDIO
rem ================================================================
:AUDIO
cls
call :HEADER "AUDIO TROUBLESHOOTER"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Service status:%R%
call :SVCSTATUS AudioEndpointBuilder "Audio Endpoint Builder"
call :SVCSTATUS Audiosrv "Windows Audio"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Sound devices detected by Windows:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Sound -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName,Manufacturer | Format-Table -AutoSize"
echo.
echo  %BYLW%?%R%  %WHT%Restart the Windows Audio services?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Restarting Windows Audio...%R%
call :SPINNER 1 "Restarting audio services..."
net stop Audiosrv /y >nul 2>&1
net stop AudioEndpointBuilder /y >nul 2>&1
net start AudioEndpointBuilder >nul 2>&1
net start Audiosrv >nul 2>&1
call :SPINSTOP
call :CHECKSVC AudioEndpointBuilder "Audio Endpoint Builder"
call :CHECKSVC Audiosrv "Windows Audio"
sc query Audiosrv 2>nul | findstr /C:": 4  " >nul
if errorlevel 1 goto AUDIO_FAIL
call :VERDICT FIXED "Audio services are running again."
call :RESTARTNOTE NO
goto AUDIO_LOG
:AUDIO_FAIL
call :VERDICT NOT "Audio services failed to start."
call :RESTARTNOTE YES
:AUDIO_LOG
echo [%date% %time%] Audio repair >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  2. VIDEO PLAYBACK
rem ================================================================
:VIDEO
cls
call :HEADER "VIDEO PLAYBACK"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Display adapters:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Display -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName,Manufacturer | Format-Table -AutoSize"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%GPU driver details:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_VideoController | Select-Object Name,DriverVersion,DriverDate,VideoModeDescription | Format-Table -AutoSize"
echo.
echo  %BYLW%Tip:%R%  %WHT%Video stuttering or black playback? Update the GPU driver,%R%
echo  %WHT%disable hardware acceleration in the player, or change refresh rate.%R%
echo.
pause
goto MENU

rem ================================================================
rem  3. WINDOWS MEDIA PLAYER
rem ================================================================
:WMP
cls
call :HEADER "WINDOWS MEDIA PLAYER"
echo.
set "WMPSYS=%ProgramFiles%\Windows Media Player\wmplayer.exe"
if exist "%WMPSYS%" goto WMP_OK
echo  %RED%%SYM_NO%%R%  %WHT%Windows Media Player%R%  %DIM%not found on this system%R%
goto WMP_MEDIA
:WMP_OK
echo  %BGRN%%SYM_OK%%R%  %WHT%Windows Media Player found:%R%
echo  %CYN%     %WMPSYS%%R%
:WMP_MEDIA
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Media file associations:%R%
assoc .mp3
assoc .mp4
assoc .wmv
assoc .avi
assoc .wav
echo.
echo  %BYLW%Tip:%R%  %WHT%Files opening in the wrong player? Change the default apps%R%
echo  %WHT%in Windows Settings ^> Apps ^> Default apps.%R%
echo.
pause
goto MENU

rem ================================================================
rem  4. NETWORK AND INTERNET
rem ================================================================
:NETWORK
cls
call :HEADER "NETWORK AND INTERNET"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Network adapters:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-NetAdapter -ErrorAction SilentlyContinue | Select-Object Name,Status,LinkSpeed,MacAddress | Format-Table -AutoSize"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%IP configuration:%R%
ipconfig /all
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Internet reachability and DNS:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "foreach($x in '1.1.1.1','8.8.8.8'){Write-Host ('   ' + $x + ' reachable: ' + (Test-Connection -ComputerName $x -Count 2 -Quiet))}; Resolve-DnsName www.microsoft.com -ErrorAction SilentlyContinue | Select-Object Name,Type,IPAddress | Format-Table -AutoSize"
echo.
echo  %BYLW%?%R%  %WHT%Reset Winsock, TCP/IP stack and DNS cache?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Flushing DNS cache...
ipconfig /flushdns >nul
echo  %CYN%%SYM_ARROW%%R%  Resetting Winsock...
netsh winsock reset
echo.
echo  %CYN%%SYM_ARROW%%R%  Resetting TCP/IP stack...
netsh int ip reset
echo.
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Network check after the reset:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$ok=0; foreach($x in '1.1.1.1','8.8.8.8'){ if(Test-Connection -ComputerName $x -Count 2 -Quiet){ $ok++ } }; Write-Host ('   Reachable: ' + $ok + ' of 2 test addresses.'); if($ok -eq 0){ exit 1 }"
if errorlevel 1 goto NET_FAIL
call :VERDICT FIXED "Network is reachable."
goto NET_END
:NET_FAIL
call :VERDICT NOT "Network is still unreachable."
:NET_END
call :RESTARTNOTE YES
echo [%date% %time%] Network reset >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  5. DNS FLUSH
rem ================================================================
:DNSFLUSH
cls
call :HEADER "DNS FLUSH"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%DNS servers in use:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-DnsClientServerAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object { $_.ServerAddresses } | Select-Object InterfaceAlias,ServerAddresses | Format-Table -AutoSize"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Resolver cache entries:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Write-Host ('   ' + (Get-DnsClientCache -ErrorAction SilentlyContinue | Measure-Object).Count + ' cached entries')"
echo.
echo  %BYLW%?%R%  %WHT%Flush the DNS resolver cache?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Flushing DNS cache...
ipconfig /flushdns
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$c=@(Get-DnsClientCache -ErrorAction SilentlyContinue).Count; Write-Host ('   Cache entries now: ' + $c); if($c -eq 0){ exit 0 } else { exit 1 }"
if errorlevel 1 goto DNSF_NOTCLEAR
call :VERDICT FIXED "The DNS cache is empty."
goto DNSF_END
:DNSF_NOTCLEAR
call :VERDICT FIXED "DNS cache was flushed."
:DNSF_END
call :RESTARTNOTE NO
echo [%date% %time%] DNS cache flushed >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  6. BLUETOOTH
rem ================================================================
:BLUETOOTH
cls
call :HEADER "BLUETOOTH"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Bluetooth devices:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Bluetooth -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName,Manufacturer | Format-Table -AutoSize"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Bluetooth service status:%R%
call :SVCSTATUS bthserv "Bluetooth Support Service"
echo.
echo  %BYLW%?%R%  %WHT%Restart the Bluetooth Support Service?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Restarting Bluetooth service...%R%
call :SPINNER 1 "Restarting Bluetooth service..."
net stop bthserv /y >nul 2>&1
net start bthserv >nul 2>&1
call :SPINSTOP
call :CHECKSVC bthserv "Bluetooth Support Service"
sc query bthserv 2>nul | findstr /C:": 4  " >nul
if errorlevel 1 goto BT_FAIL
call :VERDICT FIXED "The Bluetooth service is running again."
call :RESTARTNOTE NO
goto BT_END
:BT_FAIL
call :VERDICT NOT "The Bluetooth service failed to start."
call :RESTARTNOTE YES
:BT_END
echo [%date% %time%] Bluetooth service restarted >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  7. PRINTER
rem ================================================================
:PRINTER
cls
call :HEADER "PRINTER"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Print Spooler status:%R%
call :SVCSTATUS Spooler "Print Spooler"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Installed printers:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-Printer -ErrorAction SilentlyContinue | Select-Object Name,DriverName,PortName,PrinterStatus,WorkOffline | Format-Table -AutoSize"
echo.
echo  %BYLW%?%R%  %WHT%Restart the Print Spooler and clear stuck jobs?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Restarting Print Spooler...%R%
call :SPINNER 1 "Restarting spooler, clearing stuck jobs..."
net stop Spooler /y >nul 2>&1
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-Printer -ErrorAction SilentlyContinue | ForEach-Object { Get-PrintJob -PrinterName $_.Name -ErrorAction SilentlyContinue | Remove-PrintJob -ErrorAction SilentlyContinue }"
net start Spooler >nul 2>&1
call :SPINSTOP
call :CHECKSVC Spooler "Print Spooler"
sc query Spooler 2>nul | findstr /C:": 4  " >nul
if errorlevel 1 goto PRN_FAIL
call :VERDICT FIXED "The Print Spooler is running again."
call :RESTARTNOTE NO
goto PRN_END
:PRN_FAIL
call :VERDICT NOT "The Print Spooler failed to start."
call :RESTARTNOTE YES
:PRN_END
echo [%date% %time%] Printer spooler reset >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  8. CAMERA
rem ================================================================
:CAMERA
cls
call :HEADER "CAMERA"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Camera devices:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Camera -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName,Manufacturer | Format-Table -AutoSize"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Camera privacy setting (webcam consent):%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-ItemProperty 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam' -ErrorAction SilentlyContinue | Select-Object Value | Format-List"
echo.
echo  %BYLW%?%R%  %WHT%Rescan Plug and Play devices?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Scanning for hardware changes...
pnputil.exe /scan-devices
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$n=@(Get-PnpDevice -Class Camera -ErrorAction SilentlyContinue).Count; Write-Host ('   Camera devices found: ' + $n); if($n -gt 0){ exit 0 } else { exit 1 }"
if errorlevel 1 goto CAM_FAIL
call :VERDICT FIXED "Camera devices are detected."
call :RESTARTNOTE NO
goto CAM_END
:CAM_FAIL
call :VERDICT NOT "No camera devices found."
echo  %DIM%  Check the webcam privacy setting or the driver.%R%
call :RESTARTNOTE NO
:CAM_END
echo [%date% %time%] Camera PnP rescan >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  9. GRAPHICS DRIVER RESET
rem ================================================================
:GFXRESET
cls
call :HEADER "GRAPHICS DRIVER RESET"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Display adapters:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Display -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName | Format-Table -AutoSize"
echo.
echo  %BYLW%!%R%  %WHT%The screen may flicker or turn black for a few seconds.%R%
echo  %BYLW%?%R%  %WHT%Restart the display driver(s) now?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
set "GFX_DONE=0"
for /f "delims=" %%d in ('powershell.exe -NoProfile -Command "Get-PnpDevice -Class Display -Status OK -ErrorAction SilentlyContinue | ForEach-Object { $_.InstanceId }"') do (
    echo  %CYN%%SYM_ARROW%%R%  Restarting: "%%d"
    pnputil.exe /restart-device "%%d"
    if not errorlevel 1 set "GFX_DONE=1"
)
if "%GFX_DONE%"=="0" goto GFX_FAIL
call :VERDICT FIXED "The display driver was restarted."
call :RESTARTNOTE NO
echo [%date% %time%] Graphics driver reset >> "%LOGFILE%"
goto GFX_END
:GFX_FAIL
call :VERDICT NOT "No display adapter could be restarted."
echo  %DIM%  Try updating the driver or restarting the PC instead.%R%
call :RESTARTNOTE YES
:GFX_END
echo.
pause
goto MENU

rem ================================================================
rem  10. WINDOWS UPDATE
rem ================================================================
:UPDATE
cls
call :HEADER "WINDOWS UPDATE"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Service status:%R%
call :SVCSTATUS wuauserv "Windows Update"
call :SVCSTATUS bits "Background Intelligent Transfer (BITS)"
call :SVCSTATUS cryptsvc "Cryptographic Services"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Pending restart flags:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$p=@('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending','HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'); foreach($x in $p){Write-Host ($x + ' = ' + (Test-Path $x))}"
echo.
echo  %BYLW%?%R%  %WHT%Reset the Windows Update cache?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto UPDATE_SFC
echo  %CYN%%SYM_ARROW%%R%  Stopping update services...%R%
call :SPINNER 1 "Stopping services, moving cache aside..."
net stop wuauserv /y >nul 2>&1
net stop bits /y >nul 2>&1
net stop cryptsvc /y >nul 2>&1
rem  BUGFIX: wait up to 10 s for the services to actually release the
rem  files, so the renames below never fail on a slow machine.
for /l %%i in (1,1,10) do (
    sc query wuauserv 2>nul | findstr /C:": 4  " >nul && (sc stop wuauserv >nul 2>&1 & timeout /t 1 /nobreak >nul)
    sc query bits 2>nul | findstr /C:": 4  " >nul && (sc stop bits >nul 2>&1 & timeout /t 1 /nobreak >nul)
)
if exist "%SystemRoot%\SoftwareDistribution.old" rd /s /q "%SystemRoot%\SoftwareDistribution.old" >nul 2>&1
if exist "%SystemRoot%\SoftwareDistribution" ren "%SystemRoot%\SoftwareDistribution" "SoftwareDistribution.old" >nul 2>&1
if exist "%SystemRoot%\System32\catroot2.old" rd /s /q "%SystemRoot%\System32\catroot2.old" >nul 2>&1
if exist "%SystemRoot%\System32\catroot2" ren "%SystemRoot%\System32\catroot2" "catroot2.old" >nul 2>&1
echo  %CYN%%SYM_ARROW%%R%  Restarting update services...
net start cryptsvc >nul 2>&1
net start bits >nul 2>&1
net start wuauserv >nul 2>&1
call :SPINSTOP
call :CHECKSVC wuauserv "Windows Update"
sc query wuauserv 2>nul | findstr /C:": 4  " >nul
if errorlevel 1 goto UPDC_FAIL
call :VERDICT FIXED "Windows Update services are running again."
call :RESTARTNOTE NO
goto UPDC_END
:UPDC_FAIL
call :VERDICT NOT "Windows Update services failed to start."
call :RESTARTNOTE YES
:UPDC_END
echo [%date% %time%] Windows Update cache reset >> "%LOGFILE%"
echo.
:UPDATE_SFC
echo  %BYLW%?%R%  %WHT%Run DISM component repair and sfc /scannow?%R%  %CYN%[ Y / N ]%R%
echo  %DIM%  (This can take 10-30 minutes; DISM needs internet access)%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  %BOLD%Running DISM /RestoreHealth...%R%
DISM.exe /Online /Cleanup-Image /RestoreHealth
echo.
echo  %CYN%%SYM_ARROW%%R%  %BOLD%Running SFC /scannow...%R%
sfc.exe /scannow
echo.
call :REBOOTCHECK
if errorlevel 1 goto SFC_RESTART
call :VERDICT FIXED "System file repair completed."
call :RESTARTNOTE NO
goto SFC_END
:SFC_RESTART
call :VERDICT FIXED "System file repair completed."
call :RESTARTNOTE YES
:SFC_END
echo [%date% %time%] DISM+SFC run >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  11. BITS
rem ================================================================
:BITS
cls
call :HEADER "BITS"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%BITS service status:%R%
call :SVCSTATUS bits "Background Intelligent Transfer (BITS)"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Active BITS jobs:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-BitsTransfer -AllUsers -ErrorAction SilentlyContinue | Select-Object DisplayName,JobState,BytesTransferred,BytesTotal | Format-Table -AutoSize"
echo.
echo  %BYLW%?%R%  %WHT%Restart BITS and Windows Update services?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Restarting services...%R%
call :SPINNER 1 "Restarting BITS and Windows Update..."
net stop bits /y >nul 2>&1
net stop wuauserv /y >nul 2>&1
net start bits >nul 2>&1
net start wuauserv >nul 2>&1
call :SPINSTOP
call :CHECKSVC bits "BITS"
call :CHECKSVC wuauserv "Windows Update"
sc query bits 2>nul | findstr /C:": 4  " >nul
if errorlevel 1 goto BITS_FAIL
call :VERDICT FIXED "BITS and Windows Update are running again."
call :RESTARTNOTE NO
goto BITS_END
:BITS_FAIL
call :VERDICT NOT "BITS or Windows Update failed to start."
call :RESTARTNOTE YES
:BITS_END
echo [%date% %time%] BITS service restart >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  12. DISK CLEANUP
rem ================================================================
:DISKCLEAN
cls
call :HEADER "DISK CLEANUP"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Free space before cleanup:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' | ForEach-Object { Write-Host ('   Disk '+$_.DeviceID+'  '+[math]::Round($_.FreeSpace/1GB,1)+' GB free') }"
echo.
echo  %BYLW%?%R%  %WHT%Delete temporary files and empty the Recycle Bin?%R%  %CYN%[ Y / N ]%R%
echo  %DIM%  Only temp files are removed - personal files are untouched.%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Cleaning temporary files...%R%
call :SPINNER 1 "Removing temp files, emptying Recycle Bin..."
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$paths=@($env:TEMP,'%SystemRoot%\Temp'); foreach($p in $paths){ Get-ChildItem -LiteralPath $p -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue }; Clear-RecycleBin -Force -ErrorAction SilentlyContinue"
call :SPINSTOP
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Free space after cleanup:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' | ForEach-Object { Write-Host ('   Disk '+$_.DeviceID+'  '+[math]::Round($_.FreeSpace/1GB,1)+' GB free') }"
call :VERDICT FIXED "Cleanup completed."
call :RESTARTNOTE NO
echo [%date% %time%] Disk cleanup >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  13. SYSTEM RESTORE POINT
rem ================================================================
:RESTOPOINT
cls
call :HEADER "SYSTEM RESTORE POINT"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Existing restore points:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-ComputerRestorePoint -ErrorAction SilentlyContinue | Select-Object SequenceNumber,Description,CreationTime | Format-Table -AutoSize"
echo.
echo  %BYLW%?%R%  %WHT%Create a restore point now?%R%  %CYN%[ Y / N ]%R%
echo  %DIM%  (System Protection is enabled first if needed)%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Enabling System Protection on the system drive...
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Enable-ComputerRestore -Drive '%SystemDrive%\' -ErrorAction SilentlyContinue"
echo  %CYN%%SYM_ARROW%%R%  Creating restore point...%R%
call :SPINNER 1 "Creating restore point (this can take a minute)..."
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { Checkpoint-Computer -Description 'WinUtilKLENN restore point' -RestorePointType MODIFY_SETTINGS -ErrorAction Stop; exit 0 } catch { exit 1 }"
set "RP_RC=%errorlevel%"
call :SPINSTOP
if not "%RP_RC%"=="0" goto RESTORE_FAIL
call :VERDICT FIXED "Restore point created."
call :RESTARTNOTE NO
echo [%date% %time%] Restore point created >> "%LOGFILE%"
goto RESTORE_END
:RESTORE_FAIL
call :VERDICT NOT "Could not create a restore point."
echo  %DIM%  Open System Properties ^> System Protection, make sure protection is%R%
echo  %DIM%  enabled for the system drive, then try again.%R%
:RESTORE_END
echo.
pause
goto MENU

rem ================================================================
rem  14. BATTERY REPORT
rem ================================================================
:BATTERY
cls
call :HEADER "BATTERY REPORT"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Battery status:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$b=Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue; if(-not $b){Write-Host '   No battery detected - this looks like a desktop PC.'}else{$s=switch($b.BatteryStatus){1{'Discharging'}2{'On AC power'}3{'Fully charged'}4{'Low'}5{'Critical'}6{'Charging'}default{'Code '+$_}}; Write-Host ('   Charge: '+$b.EstimatedChargeRemaining+'%   Status: '+$s)}"
echo.
echo  %BYLW%?%R%  %WHT%Generate the full battery report (powercfg)?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Generating battery report...
powercfg /batteryreport /output "%LOGDIR%\battery-report.html" >nul 2>&1
rem  BUGFIX: verify the file really exists before declaring success.
if not exist "%LOGDIR%\battery-report.html" goto BATTERY_FAIL
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%Battery report saved:%R%
echo  %CYN%      %LOGDIR%\battery-report.html%R%
echo  %BYLW%?%R%  %WHT%Open it in the default browser?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto BATTERY_END
start "" "%LOGDIR%\battery-report.html"
goto BATTERY_END
:BATTERY_FAIL
echo  %RED%%SYM_NO%%R%  %WHT%Could not generate the battery report.%R%
echo  %DIM%  This usually means the PC has no battery (a desktop).%R%
:BATTERY_END
echo [%date% %time%] Battery report >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  15. RESTART / SHUTDOWN
rem ================================================================
:POWER
cls
call :HEADER "RESTART / SHUTDOWN"
echo  %WHT%What do you want to do?%R%
echo    %BCYN%%BOLD%1%R%  %SYM_ARROW%  %WHT%Restart the PC%R%
echo    %BCYN%%BOLD%2%R%  %SYM_ARROW%  %WHT%Shut down the PC%R%
echo    %BCYN%%BOLD%0%R%  %SYM_ARROW%  %WHT%Cancel - back to the menu%R%
echo.
choice /C 120 /N
if errorlevel 3 goto MENU
if errorlevel 2 goto POWER_OFF
echo  %BYLW%?%R%  %WHT%Restart the PC in 30 seconds?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
shutdown /r /t 30
echo [%date% %time%] Restart scheduled >> "%LOGFILE%"
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%Restart scheduled in 30 seconds.%R%
echo  %BYLW%!%R%  %WHT%To cancel, open another Command Prompt and run:  shutdown /a%R%
echo.
pause
goto MENU
:POWER_OFF
echo  %BYLW%?%R%  %WHT%Shut down the PC in 30 seconds?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto MENU
shutdown /s /t 30
echo [%date% %time%] Shutdown scheduled >> "%LOGFILE%"
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%Shutdown scheduled in 30 seconds.%R%
echo  %BYLW%!%R%  %WHT%To cancel, open another Command Prompt and run:  shutdown /a%R%
echo.
pause
goto MENU

rem ================================================================
rem  16. WINGET UPGRADE
rem ================================================================
:WINGETUP
cls
call :HEADER "WINGET UPGRADE"
winget --version >nul 2>&1
if errorlevel 1 goto WINGET_MISSING
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Available updates:%R%
winget upgrade
echo.
echo  %BYLW%?%R%  %WHT%Upgrade all packages now?%R%  %CYN%[ Y / N ]%R%
echo  %DIM%  (winget upgrade --all - some apps may need to close)%R%
choice /C YN /N
if errorlevel 2 goto MENU
echo  %CYN%%SYM_ARROW%%R%  Upgrading all packages, this can take a while...%R%
winget upgrade --all --accept-package-agreements --accept-source-agreements
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Remaining updates:%R%
winget upgrade
echo.
call :REBOOTCHECK
if errorlevel 1 goto WINGET_RESTART
call :VERDICT FIXED "The winget upgrade finished."
call :RESTARTNOTE NO
goto WINGET_END
:WINGET_RESTART
call :VERDICT FIXED "The winget upgrade finished."
call :RESTARTNOTE YES
goto WINGET_END
:WINGET_MISSING
echo  %RED%%SYM_NO%%R%  %WHT%winget is not installed.%R%
echo  %DIM%  Install 'App Installer' from the Microsoft Store, then re-run.%R%
:WINGET_END
echo [%date% %time%] winget upgrade run >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  25. SECURITY CHECK (NEW)
rem ================================================================
:SECURITY
cls
call :HEADER "SECURITY CHECK"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Windows Defender real-time protection:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { $p=Get-MpComputerStatus -ErrorAction Stop; Write-Host ('   Antivirus enabled : ' + $p.AntivirusEnabled); Write-Host ('   Real-time guard   : ' + $p.RealTimeProtectionEnabled); Write-Host ('   Signatures        : ' + $p.AntivirusSignatureLastUpdated) } catch { Write-Host '   Defender status unavailable.' }"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Firewall profiles:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-NetFirewallProfile -ErrorAction SilentlyContinue | Select-Object Name,Enabled | Format-Table -AutoSize"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%UAC (LUA) level:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$v=(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -ErrorAction SilentlyContinue).EnableLUA; $d=switch($v){0{'Disabled (INSECURE)'}1{'Enabled (default)'}default{'Unknown'}}; Write-Host ('   EnableLUA = ' + $v + '  -  ' + $d)"
echo.
echo  %BYLW%?%R%  %WHT%Run a Defender quick scan now?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto SEC_END
echo  %CYN%%SYM_ARROW%%R%  Running Defender quick scan...%R%
call :SPINNER 1 "Scanning (quick scan in progress)..."
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-MpScan -ScanType QuickScan -ErrorAction SilentlyContinue"
call :SPINSTOP
call :VERDICT FIXED "Defender quick scan finished."
call :RESTARTNOTE NO
echo [%date% %time%] Security check + Defender quick scan >> "%LOGFILE%"
:SEC_END
echo.
pause
goto MENU

rem ================================================================
rem  17. YOINKS - VIDEO DOWNLOADER (npm)
rem ================================================================
:YOINK
cls
call :HEADER "YOINKS - VIDEO DOWNLOADER"
echo  %WHT%Download videos from YouTube, X, Instagram, Threads, TikTok%R%
echo  %WHT%and 1,800+ other sites - right from your terminal.%R%
echo  %DIM%  Videos are saved to your Downloads folder.%R%
echo.
call :NPMSETUP yoinks yoinks "yoinks video downloader"
if errorlevel 1 goto YOINK_END
echo.
echo  %BOLD%%CYN%  Choose how to launch yoinks:%R%
echo     %BCYN%%BOLD%1%R%  %SYM_ARROW%  %WHT%CMD - opens a blank command prompt and types 'yoinks '%R%
echo     %BCYN%%BOLD%2%R%  %SYM_ARROW%  %WHT%Windows Terminal - opens a new WT window%R%
echo     %BCYN%%BOLD%0%R%  %SYM_ARROW%  %WHT%Cancel - back to main menu%R%
echo.
set "YOINK_CHOICE="
set /p "YOINK_CHOICE=%BOLD%%BWHT%  Select an option %R%%CYN%[0-2]%R%%BOLD%%BWHT%: %R%"
if not defined YOINK_CHOICE goto YOINK_END
if "%YOINK_CHOICE%"=="0" goto YOINK_END
if "%YOINK_CHOICE%"=="1" (
    echo.
    echo  %CYN%%SYM_ARROW%%R%  Opening a blank CMD window for yoinks...
    echo  %DIM%  The window opens clean and 'yoinks ' is typed automatically.%R%
    echo  %DIM%  Paste the video link, then press Enter manually.%R%
    echo  %DIM%  The script will return here only after the CMD window closes.%R%
    echo.
    powershell -NoProfile -Command "$wshell = New-Object -ComObject WScript.Shell; $p = Start-Process cmd.exe -PassThru; Start-Sleep -Milliseconds 800; $wshell.AppActivate($p.Id); Start-Sleep -Milliseconds 150; $wshell.SendKeys('yoinks ');"
    timeout /t 2 /nobreak >nul
) else if "%YOINK_CHOICE%"=="2" (
    echo.
    echo  %CYN%%SYM_ARROW%%R%  Opening Windows Terminal and running yoinks...
    echo  %DIM%  Yoinks will launch in a new WT window.%R%
    echo  %DIM%  The script will return here only after the WT window closes.%R%
    start "" /wait wt.exe new-tab --suppressApplicationTitle yoinks
) else (
    echo.
    echo  %BRED%!%R%  %WHT%Invalid selection.%R%
    pause
    goto YOINK_END
)
echo.
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%yoinks closed - videos are in your Downloads folder.%R%
echo [%date% %time%] yoinks video downloader run >> "%LOGFILE%"
:YOINK_END
echo.
pause
goto MENU

rem ================================================================
rem  18. GHGRAB - GITHUB DOWNLOADER (npm)
rem ================================================================
:GHGRAB
cls
call :HEADER "GHGRAB - GITHUB DOWNLOADER"
echo  %WHT%Browse and download files or folders from any GitHub repo,%R%
echo  %WHT%or grab release assets - without cloning the whole repo.%R%
echo.
call :NPMSETUP @ghgrab/ghgrab ghgrab "ghgrab"
if errorlevel 1 goto GHGRAB_END
echo.
echo  %CYN%%SYM_ARROW%%R%  Launching ghgrab...
echo  %DIM%  Paste a repo link (e.g. https://github.com/rust-lang/rust)%R%
echo  %DIM%  or run  ghgrab rel owner/repo  for release assets.%R%
echo.
call :RESIZE_MAX
call ghgrab
call :FITCHECK
echo.
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%ghgrab closed.%R%
echo [%date% %time%] ghgrab run >> "%LOGFILE%"
:GHGRAB_END
echo.
pause
goto MENU

rem ================================================================
rem  19. FREEBUFF - AI HELP (npm)
rem ================================================================
:FREEBUFF
cls
call :HEADER "FREEBUFF - AI HELP"
echo  %WHT%Freebuff is a free AI coding agent that runs in your terminal.%R%
echo  %WHT%Ask it about an error, or get any repair step explained.%R%
echo.
call :NPMSETUP freebuff freebuff "freebuff"
if errorlevel 1 goto FREEBUFF_END
echo.
echo  %CYN%%SYM_ARROW%%R%  Launching freebuff...
echo  %DIM%  It opens in the folder the script was started from.%R%
echo.
call :RESIZE_MAX
call freebuff
call :FITCHECK
echo.
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%freebuff closed.%R%
echo [%date% %time%] freebuff run >> "%LOGFILE%"
:FREEBUFF_END
echo.
pause
goto MENU

rem ================================================================
rem  20. PROGRAM COMPATIBILITY
rem ================================================================
:COMPAT
cls
call :HEADER "PROGRAM COMPATIBILITY"
echo  %WHT%Enter the full path to an .exe file to inspect it.%R%
echo  %DIM%Example: C:\Program Files\Example\app.exe%R%
echo.
set "EXE="
set /p "EXE=%BOLD%%CYN%  Path: %R%"
if not defined EXE goto MENU
if not exist "%EXE%" goto COMPAT_ERR
echo.
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$f=Get-Item -LiteralPath $env:EXE; $v=$f.VersionInfo; [pscustomobject]@{Path=$f.FullName;FileVersion=$v.FileVersion;Product=$v.ProductName;Company=$v.CompanyName;SizeMB=[math]::Round($f.Length/1MB,2)} | Format-List"
echo.
echo  %BYLW%Tip:%R%  %WHT%Check for a current version of the application and%R%
echo  %WHT%only use compatibility settings when necessary.%R%
echo.
pause
goto MENU
:COMPAT_ERR
echo.
echo  %RED%%SYM_NO%%R%  %WHT%File not found:%R%  %BCYN%%EXE%%R%
echo.
pause
goto MENU

rem ================================================================
rem  21. COMPLETE DIAGNOSTICS
rem ================================================================
:ALL
cls
call :HEADER "COMPLETE DIAGNOSTICS"
echo  %BWHT%Scanning the system, this can take a few moments...%R%
echo.
echo  %BOLD%%CYN%[1] AUDIO%R%
call :SVCSTATUS Audiosrv "Windows Audio"
call :SVCSTATUS AudioEndpointBuilder "Audio Endpoint Builder"
echo.
echo  %BOLD%%CYN%[2] NETWORK%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-NetAdapter -ErrorAction SilentlyContinue | Select-Object Name,Status,LinkSpeed | Format-Table -AutoSize"
echo.
echo  %BOLD%%CYN%[3] PRINTER%R%
call :SVCSTATUS Spooler "Print Spooler"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-Printer -ErrorAction SilentlyContinue | Select-Object Name,PrinterStatus | Format-Table -AutoSize"
echo.
echo  %BOLD%%CYN%[4] WINDOWS UPDATE%R%
call :SVCSTATUS wuauserv "Windows Update"
call :SVCSTATUS bits "BITS"
call :SVCSTATUS cryptsvc "Cryptographic Services"
echo.
echo  %BOLD%%CYN%[5] BLUETOOTH%R%
call :SVCSTATUS bthserv "Bluetooth Support Service"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Bluetooth -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName | Format-Table -AutoSize"
echo.
echo  %BOLD%%CYN%[6] CAMERA%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-PnpDevice -Class Camera -ErrorAction SilentlyContinue | Select-Object Status,FriendlyName | Format-Table -AutoSize"
echo.
echo  %BOLD%%CYN%[7] DISPLAY / VIDEO%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_VideoController | Select-Object Name,DriverVersion | Format-Table -AutoSize"
echo.
echo  %BOLD%%CYN%[8] WINDOWS MEDIA PLAYER%R%
if exist "%ProgramFiles%\Windows Media Player\wmplayer.exe" goto ALL_WMP_OK
echo   %RED%%SYM_NO%%R%  %WHT%Windows Media Player%R%  %DIM%not installed%R%
goto ALL_DONE
:ALL_WMP_OK
echo   %BGRN%%SYM_OK%%R%  %WHT%Windows Media Player%R%  %GRN%installed%R%
:ALL_DONE
echo.
echo  %BGGRN%%BLK%[ DONE ]%R%  %BGRN%Complete diagnostics finished.%R%
echo [%date% %time%] Complete diagnostics >> "%LOGFILE%"
echo.
pause
goto MENU

rem ================================================================
rem  22. SYSTEM SUMMARY
rem ================================================================
:SUMMARY
cls
call :HEADER "SYSTEM SUMMARY"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Computer:  %R%%BCYN%%COMPUTERNAME%%R%
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%User:      %R%%BCYN%%USERNAME%%R%
echo.
ver
echo.
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_OperatingSystem | Select-Object Caption,Version,BuildNumber,OSArchitecture | Format-List"
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Memory and disk:%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$os=Get-CimInstance Win32_OperatingSystem; $tm=[math]::Round($os.TotalVisibleMemorySize/1MB,1); $fm=[math]::Round($os.FreePhysicalMemory/1MB,1); Write-Host ('   RAM free: '+$fm+' GB / '+$tm+' GB total'); Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' | ForEach-Object { Write-Host ('   Disk '+$_.DeviceID+'  '+[math]::Round($_.FreeSpace/1GB,1)+' GB free / '+[math]::Round($_.Size/1GB,1)+' GB total') }"
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%PowerShell version:%R%
powershell.exe -NoProfile -Command "$PSVersionTable.PSVersion.ToString()"
echo.
echo  %DIM%  Log: %LOGFILE%%R%
echo.
pause
goto MENU

rem ================================================================
rem  23. CHECK FOR UPDATES
rem ================================================================
:UPDATECHECK
cls
call :HEADER "CHECK FOR UPDATES"
echo  %DIM%  Checking the GitHub repository for the latest release...%R%
set "UPD_STATUS="
rem  SECURITY: TLS 1.2 forced on every web call.
for /f "delims=" %%v in ('powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; try { $r=Invoke-RestMethod -Uri 'https://api.github.com/repos/sanguirIS/WinUtilKLENN/releases/latest' -Headers @{ 'User-Agent'=('WinUtilKLENN/'+'%VERSION:~1%') } -TimeoutSec 15; $localVersion='%VERSION%'.TrimStart('v'); $remoteVersion=$r.tag_name.TrimStart('v'); try { $lv=[version]$localVersion; $rv=[version]$remoteVersion } catch { $lv=[version]'0.0.0.1'; $rv=[version]'0.0.0.2'; $rawLocal=$localVersion; $rawRemote=$remoteVersion }; if ($rv -gt $lv) { 'NEW:'+$r.tag_name } elseif ($rv -lt $lv) { 'LOCAL' } else { 'SAME' } } catch { 'ERR' }"') do set "UPD_STATUS=%%v"
echo.
if "%UPD_STATUS%"=="SAME" goto UPD_SAME
if "%UPD_STATUS%"=="LOCAL" goto UPD_LOCAL
if "%UPD_STATUS:~0,4%"=="NEW:" goto UPD_NEW
goto UPD_ERR
:UPD_SAME
echo  %BGRN%%SYM_OK%%R%  %WHT%You are running the latest version%R%  %BCYN%%VERSION%%R%
echo [%date% %time%] Update check: up to date (%VERSION%) >> "%LOGFILE%"
goto UPD_END
:UPD_LOCAL
echo  %BGRN%%SYM_OK%%R%  %WHT%You are running %VERSION%, which is newer than%R%
echo  %WHT%the latest GitHub release. Nothing to update.%R%
echo [%date% %time%] Update check: local version ahead of latest release >> "%LOGFILE%"
goto UPD_END
:UPD_NEW
set "UPD_NEW=%UPD_STATUS:~4%"
echo  %BYLW%!%R%  %WHT%A newer version is available:%R%  %BCYN%%UPD_NEW%%R%
echo  %DIM%  You are running %VERSION%.%R%
echo  %BYLW%?%R%  %WHT%Open the release page in your browser?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto UPD_END
start "" "https://github.com/sanguirIS/WinUtilKLENN/releases/latest"
echo [%date% %time%] Update check: new version %UPD_NEW% >> "%LOGFILE%"
goto UPD_END
:UPD_ERR
echo  %RED%%SYM_NO%%R%  %WHT%Could not check for updates.%R%
echo  %DIM%  Check your internet connection, or visit:%R%
echo  %CYN%      https://github.com/sanguirIS/WinUtilKLENN/releases%R%
echo [%date% %time%] Update check failed >> "%LOGFILE%"
:UPD_END
echo.
pause
goto MENU

rem ================================================================
rem  24. CHRIS TITUS TECH WINUTIL
rem ================================================================
:WINUTIL
cls
call :HEADER "CHRIS TITUS TECH WINUTIL"
echo  %WHT%Step-by-step setup of the WinUtil toolbox.%R%
echo  %DIM%  Chris Titus Tech - github.com/ChrisTitusTech/winutil%R%
echo.
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Step 1 - Documents\PowerShell folder%R%
echo  %BYLW%?%R%  %WHT%Create it if it does not exist?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto WINUTIL_STEP2
powershell.exe -NoProfile -Command "$d=Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'PowerShell'; if (Test-Path $d) { Write-Host ('   Already exists: ' + $d) } else { New-Item -ItemType Directory -Path $d | Out-Null; Write-Host ('   Created: ' + $d) }"
if errorlevel 1 goto WINUTIL_STEP1FAIL
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%PowerShell folder ready.%R%
echo.
goto WINUTIL_STEP2
:WINUTIL_STEP1FAIL
echo  %RED%%SYM_NO%%R%  %WHT%Could not create the folder. Check permissions.%R%
echo.
:WINUTIL_STEP2
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Step 2 - Download winutil.ps1%R%
echo   %DIM%[1] Pinned:%R%  %CYN%winutil.ps1 (release 26.08.04)%R%
echo   %DIM%[2] Latest:%R%  %CYN%winutil.ps1 (latest release)%R%
echo  %BYLW%?%R%  %WHT%Download it into Documents\PowerShell?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto WINUTIL_STEP3
echo.
echo   %WHT%Which version?%R%
echo     %BCYN%%BOLD%1%R%  %SYM_ARROW%  %WHT%Pinned release 26.08.04%R%
echo     %BCYN%%BOLD%2%R%  %SYM_ARROW%  %WHT%Latest release%R%
choice /C 12 /N
if errorlevel 2 goto WINUTIL_DL_LATEST
set "WINUTIL_URL=https://github.com/ChrisTitusTech/winutil/releases/download/26.08.04/winutil.ps1"
echo  %CYN%%SYM_ARROW%%R%  Downloading winutil.ps1 (26.08.04)...
goto WINUTIL_DL
:WINUTIL_DL_LATEST
set "WINUTIL_URL=https://github.com/ChrisTitusTech/winutil/releases/latest/download/winutil.ps1"
echo  %CYN%%SYM_ARROW%%R%  Downloading winutil.ps1 (latest)...
:WINUTIL_DL
rem  SECURITY: TLS 1.2 forced on the download as well.
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; $d=Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'PowerShell'; New-Item -ItemType Directory -Force -Path $d | Out-Null; Invoke-WebRequest -Uri '%WINUTIL_URL%' -OutFile (Join-Path $d 'winutil.ps1') -UseBasicParsing; $f=Get-Item (Join-Path $d 'winutil.ps1'); Write-Host ('   Saved: ' + $f.FullName + '  (' + [math]::Round($f.Length/1KB,1) + ' KB)') "
if errorlevel 1 goto WINUTIL_DLFAIL
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%winutil.ps1 downloaded.%R%
echo [%date% %time%] WinUtil script downloaded >> "%LOGFILE%"
goto WINUTIL_STEP3
:WINUTIL_DLFAIL
echo  %RED%%SYM_NO%%R%  %WHT%Download failed. Check your internet connection or the URL.%R%
echo.
:WINUTIL_STEP3
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Step 3 - PowerShell execution policy%R%
powershell.exe -NoProfile -Command "try { $p=(Get-ExecutionPolicy -Scope Process).ToString() } catch { $p='unknown' }; Write-Host ('   Current policy (Process scope): ' + $p); if ($p -eq 'Restricted') { Write-Host '   Policy is Restricted - a Bypass is recommended.' } elseif ($p -ne 'unknown') { Write-Host '   No change needed.' }"
echo  %BYLW%?%R%  %WHT%Set-ExecutionPolicy Bypass -Scope Process?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto WINUTIL_STEP4
powershell.exe -NoProfile -Command "Set-ExecutionPolicy -Scope Process Bypass -Force"
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%Execution policy set to Bypass (current process).%R%
echo.
:WINUTIL_STEP4
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Step 4 - winget install --id ChrisTitusTech.winutil%R%
winget --version >nul 2>&1
if errorlevel 1 goto WINUTIL_NOWINGET
echo  %BYLW%?%R%  %WHT%Run:  winget install --id ChrisTitusTech.winutil%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto WINUTIL_STEP5
echo  %CYN%%SYM_ARROW%%R%  Installing WinUtil via winget...%R%
call :SPINNER 1 "Installing via winget (this can take a minute)..."
winget install --id ChrisTitusTech.winutil --accept-package-agreements --accept-source-agreements
set "WG_RC=%errorlevel%"
call :SPINSTOP
rem  BUGFIX: check winget's own errorlevel too - some builds do not
rem  print "No package found" but still fail the install.
winget show --id ChrisTitusTech.winutil >nul 2>&1
if errorlevel 1 goto WINUTIL_WINFAIL
if not "%WG_RC%"=="0" goto WINUTIL_WINFAIL
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%WinUtil installed via winget.%R%
echo [%date% %time%] winget install ChrisTitusTech.winutil >> "%LOGFILE%"
goto WINUTIL_STEP5
:WINUTIL_WINFAIL
echo  %RED%%SYM_NO%%R%  %WHT%winget could not find the package 'ChrisTitusTech.winutil'.%R%
echo   %DIM%  It is not in the official winget sources. Use Step 2 (download)%R%
echo   %DIM%  and Step 5 (irm christitus.com/win ^| iex) instead.%R%
echo.
goto WINUTIL_STEP5
:WINUTIL_NOWINGET
echo   %RED%%SYM_NO%%R%  %WHT%winget is not installed.%R%
echo  %BYLW%?%R%  %WHT%Open the Microsoft Store page for 'App Installer'?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 goto WINUTIL_STEP5
start "" "ms-windows-store://pdp/?productid=9NBLGGH4NNS1"
echo  %CYN%%SYM_ARROW%%R%  Store page opened - install 'App Installer' there, then re-run this tool.%R%
echo [%date% %time%] Opened App Installer store page >> "%LOGFILE%"
echo.
:WINUTIL_STEP5
echo  %BWHT%%SYM_BULLET%%R%  %BOLD%Step 5 - Launch WinUtil%R%
echo   %DIM%Command:%R%  %CYN%irm https://christitus.com/win ^| iex%R%
echo  %BYLW%?%R%  %WHT%Launch WinUtil now in an elevated PowerShell?%R%  %CYN%[ Y / N ]%R%
echo   %DIM%  Close the WinUtil window to return to this menu.%R%
choice /C YN /N
if errorlevel 2 goto WINUTIL_END
echo  %CYN%%SYM_ARROW%%R%  Launching WinUtil...%R%
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "irm https://christitus.com/win | iex"
echo [%date% %time%] WinUtil launched >> "%LOGFILE%"
:WINUTIL_END
echo.
echo  %BGGRN%%BLK%[ DONE ]%R%  %BGRN%WinUtil setup finished.%R%
echo.
pause
goto MENU

rem ================================================================
rem  EXIT
rem ================================================================
:END
echo.
echo  %RULE_BIG%
echo  %BGRN%%SYM_OK%%R%  %BWHT%WinUtilKLENN closed. Thank you!%R%
echo  %DIM%   Log saved to: %LOGFILE%%R%
echo  %DIM%   Tip: use option 23 to check for a newer version.%R%
echo  %DIM%  WinUtilKLENN  Copyright (C) 2026 sanguirIS%R%
echo  %DIM%  This program comes with ABSOLUTELY NO WARRANTY.%R%
echo  %DIM%  Free software: redistribute under the GNU GPL v3 - see LICENSE%R%
echo  %RULE_BIG%
echo [%date% %time%] Closed >> "%LOGFILE%"
endlocal
exit /b 0

rem ================================================================
rem  HELPER ROUTINES
rem ================================================================

rem  Auto-fit check: re-measures the console width ONLY when it changed
rem  since the last measurement (e.g. the user resized the window). This
rem  replaces the old per-screen :RESIZE PowerShell spawn, so every
rem  screen redraw is now instant.
:FITCHECK
set "NOW_W="
for /f %%w in ('powershell -NoProfile -Command "try { Write-Host ([Math]::Max(60,(Get-Host).UI.RawUI.WindowSize.Width)) } catch { Write-Host 68 }"') do set "NOW_W=%%w"
if not defined NOW_W set "NOW_W=68"
if "%NOW_W%"=="%CON_WIDTH%" goto :eof
set "CON_WIDTH=%NOW_W%"
for /f "tokens=1-2 delims=|" %%a in ('powershell -NoProfile -Command "$h=[char]0x2500; Write-Output (($h.ToString()*([Math]::Max(60,%CON_WIDTH%)-2))+'|'+($h.ToString()*36))"') do (
    set "RULE_BIG=%%a"
    set "RULE_SMALL=%%b"
)
goto :eof

rem  One-time window sizing (called before the menu loop only). The
rem  window is grown to fit the screen (capped 68x50) and the buffer is
rem  matched so no scrollbar appears. Runs once, not per screen.
:RESIZE
powershell.exe -NoProfile -Command "try { $ui=(Get-Host).UI.RawUI; $max=$ui.MaxWindowSize; $wW=[Math]::Min(68,$max.Width); $wH=[Math]::Min(50,$max.Height); $b=$ui.BufferSize; if($b.Width -lt $wW){ $b.Width=$wW; $b.Height=50; $ui.BufferSize=$b }; $w=$ui.WindowSize; $w.Width=$wW; $w.Height=$wH; $ui.WindowSize=$w; $b=$ui.BufferSize; $b.Width=$wW; $b.Height=50; $ui.BufferSize=$b } catch {}" >nul 2>&1
goto :eof

rem  Animated anime-style boot banner: gradient title, spinning loader,
rem  typewriter tagline. Pure ANSI, no external files.
:ANIMEBOOT
echo.
echo  %BMAG%%SYM_STAR%%SYM_STAR% %R%%BOLD%%ESC%[38;2;255;105;180m   WINUTILKLENN %R% %BMAG%%SYM_STAR%%SYM_STAR%%R%
echo  %DIM%        %ESC%[38;2;0;200;255mv%VERSION% - anime-neon build%R%
echo.
echo  %BCYN%[%R% %BGRN%Loading%R%
set /a AB_D=0
:AB_LOOP
<nul set /p "=%R%  %ESC%[38;2;255;105;180m%SYM_BULLET%%R%"
timeout /t 1 /nobreak >nul
set /a AB_D+=1
if %AB_D% lss 6 goto AB_LOOP
echo %R%  %BGRN% OK%R%
echo.
echo  %BCYN%~%R% %BWHT%D%R%
<nul set /p "=%BCYN%~%R% %BWHT%ia%R%"
<nul set /p "=%BCYN%~%R% %BWHT%gn%R%"
<nul set /p "=%BCYN%~%R% %BWHT%os%R%"
<nul set /p "=%BCYN%~%R% %BWHT%tic%R%"
<nul set /p "=%BCYN%~%R% %BWHT%s a%R%"
<nul set /p "=%BCYN%~%R% %BWHT%nd%R%"
<nul set /p "=%BCYN%~%R% %BWHT% rep%R%"
<nul set /p "=%BCYN%~%R% %BWHT%air%R%"
<nul set /p "=%BCYN%~%R% %BWHT% fo%R%"
<nul set /p "=%BCYN%~%R% %BWHT%r W%R%"
<nul set /p "=%BCYN%~%R% %BWHT%indo%R%"
<nul set /p "=%BCYN%~%R% %BWHT%ws 1%R%"
<nul set /p "=%BCYN%~%R% %BWHT%0 / 1%R%"
<nul set /p "=%BCYN%~%R% %BWHT%1 %R%%BGRN%%SYM_OK%%R%"
echo.
echo.
timeout /t 1 /nobreak >nul
goto :eof

rem  Animated spinner used while long operations run.
rem  %1 ignored (compat), %2 = label.
:SPINNER
set "SPIN_LABEL=%~2"
set "SPIN_ON=1"
echo  %CYN%%SYM_ARROW%%R%  %BWHT%%SPIN_LABEL%%R%
goto :eof

rem  Stops the spinner line and prints a completion mark.
:SPINSTOP
set "SPIN_ON=0"
echo  %BGRN%%SYM_OK%%R%  %GRN%done.%R%
goto :eof

:HEADER
echo.
echo  %BOLD%%BGBLU%%WHT%  %~1  %R%  %RULE_SMALL%
echo.
goto :eof

rem  Locale-safe service state badge. %1 = service, %2 = display label.
:SVCSTATUS
set "SVCSVC=%~1"
set "SVCLABEL=%~2"
set "SVCSTATE="
sc query "%SVCSVC%" >nul 2>&1
if errorlevel 1 goto SVCNF
for /f "tokens=4" %%a in ('sc query "%SVCSVC%" 2^>nul ^| findstr /C:"STATE"') do set "SVCSTATE=%%a"
if /i "%SVCSTATE%"=="RUNNING" goto SVC_OK
if /i "%SVCSTATE%"=="STOPPED" goto SVC_STOPPED
sc query "%SVCSVC%" 2>nul | findstr /C:": 4  " >nul && goto SVC_OK
sc query "%SVCSVC%" 2>nul | findstr /C:": 1  " >nul && goto SVC_STOPPED
goto SVC_UNKNOWN
:SVCNF
echo   %BGYLW%%BLK%[ ? ]%R%  %YLW%%SVCLABEL%  %DIM%(service not found)%R%
goto :eof
:SVC_STOPPED
echo   %BGRED%%WHT%[ STOPPED ]%R%  %RED%%SYM_NO%%R%  %BWHT%%SVCLABEL%%R%
goto :eof
:SVC_OK
echo   %BGGRN%%BLK%[ RUNNING ]%R%  %BGRN%%SYM_OK%%R%  %BWHT%%SVCLABEL%%R%
goto :eof
:SVC_UNKNOWN
echo   %BGYLW%%BLK%[ ? ]%R%  %YLW%%SVCLABEL%  %DIM%(state unknown)%R%
goto :eof

rem  Checks if a service is running. %1 = service, %2 = display label.
:CHECKSVC
sc query "%~1" 2>nul | findstr /C:": 4  " >nul
if errorlevel 1 goto CS_FAIL
echo   %BGRN%%SYM_OK%%R%  %BWHT%%~2%R%  %GRN%is running%R%
goto :eof
:CS_FAIL
echo   %RED%%SYM_NO%%R%  %BWHT%%~2%R%  %DIM%not running%R%
goto :eof

rem  Final verdict after a repair. %1 = FIXED or NOT, %2 = message.
:VERDICT
if /i "%~1"=="FIXED" goto VERDICT_OK
echo  %BGRED%%WHT%[ NOT FIXED ]%R%  %RED%%~2%R%
goto :eof
:VERDICT_OK
echo  %BGGRN%%BLK%[ FIXED ]%R%  %BGRN%%~2%R%
goto :eof

rem  Restart requirement after a repair. %1 = YES or NO.
:RESTARTNOTE
if /i "%~1"=="YES" goto RESTART_YES
echo  %BGRN%%SYM_OK%%R%  %WHT%No restart needed - the fix is active now.%R%
goto :eof
:RESTART_YES
echo  %BYLW%!%R%  %WHT%A restart is required to apply the changes.%R%
goto :eof

rem  Checks for pending-reboot flags; sets errorlevel 1 if a reboot is pending.
:REBOOTCHECK
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$p=@('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending','HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'); $any=$false; foreach($x in $p){ if(Test-Path $x){ $any=$true } }; if($any){ Write-Host '   Pending restart detected.'; exit 1 } else { Write-Host '   No pending restart detected.'; exit 0 }"
goto :eof

rem  SECURITY: rotates the log file so it never grows unbounded (512 KB
rem  cap). Old logs are kept as .old, the newest stays active.
:SECLOGROTATE
if not exist "%LOGFILE%" goto :eof
for %%s in ("%LOGFILE%") do if %%~zs gtr 524288 (
    if exist "%LOGFILE%.old" del /q "%LOGFILE%.old" >nul 2>&1
    move /y "%LOGFILE%" "%LOGFILE%.old" >nul 2>&1
)
goto :eof

rem  Makes sure an npm tool is installed. %1 = npm package, %2 = binary,
rem  %3 = display label. Installs Node.js via winget if npm is missing,
rem  installs the package globally if the binary is missing. Returns
rem  errorlevel 0 when the tool is ready to launch.
:NPMSETUP
where npm >nul 2>&1
if errorlevel 1 goto NPM_MISSING
where "%~2" >nul 2>&1
if errorlevel 1 goto NPM_INSTALL
echo  %BGRN%%SYM_OK%%R%  %WHT%%~3%R%  %GRN%already installed - launching%R%
echo [%date% %time%] NPM setup: %~3 found and ready >> "%LOGFILE%"
exit /b 0
:NPM_INSTALL
echo  %BYLW%!%R%  %WHT%%~3%R%  %DIM%is not installed yet%R%
echo  %BYLW%?%R%  %WHT%Install it globally via npm now?%R%  %CYN%[ Y / N ]%R%
echo  %DIM%  Command:  npm install -g %~1 %R%
choice /C YN /N
if errorlevel 2 (
    echo [%date% %time%] NPM setup: User cancelled installation of %~3 >> "%LOGFILE%"
    exit /b 1
)
echo  %CYN%%SYM_ARROW%%R%  Installing %~1 (can take a minute)...
echo [%date% %time%] NPM setup: Starting installation of %~1 >> "%LOGFILE%"
npm install -g "%~1"
if errorlevel 1 goto NPM_INSTALL_FAIL
where "%~2" >nul 2>&1
if errorlevel 1 goto NPM_INSTALL_FAIL
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%%~3%R%  %WHT%installed.%R%
echo [%date% %time%] NPM setup: %~3 installed successfully >> "%LOGFILE%"
exit /b 0
:NPM_INSTALL_FAIL
echo  %RED%%SYM_NO%%R%  %WHT%Install failed - check the internet connection.%R%
echo [%date% %time%] NPM setup: Failed to install %~3 >> "%LOGFILE%"
exit /b 1
:NPM_MISSING
echo  %RED%%SYM_NO%%R%  %WHT%npm / Node.js was not found on this system.%R%
echo  %BYLW%?%R%  %WHT%Install Node.js LTS via winget now?%R%  %CYN%[ Y / N ]%R%
choice /C YN /N
if errorlevel 2 (
    echo [%date% %time%] NPM setup: User cancelled Node.js installation >> "%LOGFILE%"
    exit /b 1
)
echo  %CYN%%SYM_ARROW%%R%  Installing Node.js LTS (winget)...
echo [%date% %time%] NPM setup: Starting Node.js LTS installation via winget >> "%LOGFILE%"
call :SPINNER 1 "Installing Node.js LTS..."
winget install --id OpenJS.NodeJS.LTS -e --accept-source-agreements --accept-package-agreements
set "NODE_RC=%errorlevel%"
call :SPINSTOP
if not "%NODE_RC%"=="0" goto NPM_NODE_FAIL
call :REFRESHPATH
where npm >nul 2>&1
if errorlevel 1 goto NPM_NODE_FAIL
echo  %BGGRN%%BLK%[ OK ]%R%  %BGRN%Node.js installed - npm is ready.%R%
echo [%date% %time%] NPM setup: Node.js installed successfully, npm available >> "%LOGFILE%"
exit /b 0
:NPM_NODE_FAIL
echo  %RED%%SYM_NO%%R%  %WHT%Node.js could not be installed automatically.%R%
echo  %DIM%  Install it from https://nodejs.org, then re-run this option.%R%
echo [%date% %time%] NPM setup: Failed to install Node.js >> "%LOGFILE%"
exit /b 1

rem  Re-reads PATH from the registry into this session (used after an
rem  automatic Node.js install so npm is found without a restart).
:REFRESHPATH
set "SYS_PATH="
set "USR_PATH="
for /f "skip=2 tokens=2,*" %%A in ('reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path 2^>nul') do set "SYS_PATH=%%B"
for /f "skip=2 tokens=2,*" %%A in ('reg query "HKCU\Environment" /v Path 2^>nul') do set "USR_PATH=%%B"
if defined SYS_PATH set "PATH=%SYS_PATH%"
if defined USR_PATH set "PATH=%PATH%;%USR_PATH%"
goto :eof

rem  Expands the console to the largest available size before launching
rem  the full-screen TUI tools (yoinks / ghgrab / freebuff). The
rem  :FITCHECK routine re-measures the window after the tool closes.
:RESIZE_MAX
powershell.exe -NoProfile -Command "try { $ui=(Get-Host).UI.RawUI; $max=$ui.MaxWindowSize; $b=$ui.BufferSize; $b.Width=$max.Width; $b.Height=$max.Height; $ui.BufferSize=$b; $w=$ui.WindowSize; $w.Width=$max.Width; $w.Height=$max.Height; $ui.WindowSize=$w } catch {}" >nul 2>&1
goto :eof
